# Generated by Django 2.2.13 on 2020-06-27 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fuel', models.IntegerField(choices=[(0, 'Water'), (1, 'Natural Gas'), (2, 'Electricity')], default=0)),
                ('unit', models.IntegerField(choices=[(0, 'm3'), (1, 'kWh')], default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_consumption.Building')),
            ],
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=6, max_digits=12)),
                ('date_time', models.DateTimeField()),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='energy_consumption.Meter')),
            ],
        ),
    ]
